version: '3.9'

volumes:
  sqlvolume:
    external: true

services:
  mysql-server:
    image: mysql
    container_name: mysql-db-dev
    restart: always
    volumes:
        - sqlvolume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=userapidb
    networks:
      - bridge500
    healthcheck:
      #test: "/etc/init.d/mysql status"
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 120

  webapi:
    environment:
      - DB_HOST=mysql-server
      - DB_USER=root
      - DB_PASS=123456
    build: ./
    container_name: notes-api-dev
    restart: always
    ports:
      - "3000:3000"
    networks:
      - bridge500
    depends_on:
      mysql-server:
        condition: service_healthy

networks:
  bridge500:
    external: true
